# Generated by Django 4.1.7 on 2023-02-19 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='brand',
        ),
        migrations.AlterField(
            model_name='casts_details',
            name='end_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='casts_details',
            name='start_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
